# Generated by Django 5.1.1 on 2024-11-17 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0005_jogos_idiomaaudio_jogos_imgjogo_alter_jogos_promocao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdProduto', models.PositiveIntegerField(default=0)),
                ('precoTotal', models.FloatField(default=0.0)),
                ('jogos', models.ManyToManyField(to='jogos.jogos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
