# Generated by Django 5.1.1 on 2024-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('avaliacao', models.CharField(max_length=100)),
                ('promocao', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('imgUrl', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
