# Generated by Django 5.1.1 on 2024-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogos',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterField(
            model_name='jogos',
            name='imgUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
