# Generated by Django 5.1.1 on 2024-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_jogos_options_alter_jogos_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
