# Generated by Django 5.1.1 on 2024-10-31 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_alter_jogos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='lancamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
