# Generated by Django 5.1.1 on 2024-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_jogos_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='idiomaAudio',
            field=models.CharField(default='idioma.default', max_length=100),
        ),
        migrations.AddField(
            model_name='jogos',
            name='imgJogo',
            field=models.CharField(default='img.url', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='promocao',
            field=models.CharField(max_length=3),
        ),
    ]
