# Generated by Django 5.1.1 on 2024-11-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_jogos_idiomaaudio_jogos_imgjogo_alter_jogos_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
